{
  "formatVersion": "1.1",
  "component": {
    "group": "com.simpsdk.sdk",
    "module": "simp_release",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.1.3.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.1.3.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.1.3.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.1.3.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "simp_release-1.1.3.aar",
          "url": "simp_release-1.1.3.aar",
          "size": 4321972,
          "sha512": "8e0ea56c53fb229ec3cc3e3679e797fd7f02a7817e28e5f4bb9c918f2e6c7164db04f4202d7bd70f5e11fff714a3c891260e67b7dc1604278c7c08e05646f3e0",
          "sha256": "878aaf28a2f089c6450079fe352ae2f772d5960355c19246ad4b3d710f69f141",
          "sha1": "62e4f11d42a940884da94af931cd5c5713aeede5",
          "md5": "1b41ae26f2450b5e0bb9c052115a5905"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.1.3.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.1.3.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.1.3.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.1.3.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "simp_release-1.1.3.aar",
          "url": "simp_release-1.1.3.aar",
          "size": 4321972,
          "sha512": "8e0ea56c53fb229ec3cc3e3679e797fd7f02a7817e28e5f4bb9c918f2e6c7164db04f4202d7bd70f5e11fff714a3c891260e67b7dc1604278c7c08e05646f3e0",
          "sha256": "878aaf28a2f089c6450079fe352ae2f772d5960355c19246ad4b3d710f69f141",
          "sha1": "62e4f11d42a940884da94af931cd5c5713aeede5",
          "md5": "1b41ae26f2450b5e0bb9c052115a5905"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simp_release-1.1.3-sources.jar",
          "url": "simp_release-1.1.3-sources.jar",
          "size": 1146,
          "sha512": "1e8b170e410f6cd7336deeec5861e870959568f09291895867d0705933647767dcdc826404a94b9582fd72a132edfca7440da37d05edf62d7b1a26dbd71d426e",
          "sha256": "7541e251c63178b7fc781a3d55a502897e86ff5c26ffd15175d8d53feb35bbc5",
          "sha1": "832b333e04394576958e0dd0c2243a1e30d0199b",
          "md5": "d8b69ab6a632e293ab25bdc0d6dce2e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simp_release-1.1.3-javadoc.jar",
          "url": "simp_release-1.1.3-javadoc.jar",
          "size": 261687,
          "sha512": "e1a6d33dda75d144f4e55191c618680bb96eaa38d844a6997ae3c2636b285645deb0b086688b72e6f364ace0729f67f8cc5e1f7299e04b1543dd49d0c30411a3",
          "sha256": "d9aa77c8f41815c9159984c3501460f6dfc6604ab5916a8ee4e35dee3c346d16",
          "sha1": "2166d022d582188b28e846f39b36a1082b5f9066",
          "md5": "7c80635e3e18a560f1391d955845529e"
        }
      ]
    }
  ]
}
