{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 266640,
          "sha512": "dbe26689da19e4f9325cc1f83da4222e343c9e375d8b9593b5431a63a80bdbd017c0f7d95f4378377f3224156db02f7663d9777812fe09955ef10e65ab3a6c03",
          "sha256": "305fb83ac8b3bd758965760e332201529c2fe12417a6f5daf74dcabab52ecdc3",
          "sha1": "c2937d34f5f247a21dc07a1c6e40611e1c695501",
          "md5": "b7110ec9c262c8a1fbb7687b9a704015"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 266640,
          "sha512": "dbe26689da19e4f9325cc1f83da4222e343c9e375d8b9593b5431a63a80bdbd017c0f7d95f4378377f3224156db02f7663d9777812fe09955ef10e65ab3a6c03",
          "sha256": "305fb83ac8b3bd758965760e332201529c2fe12417a6f5daf74dcabab52ecdc3",
          "sha1": "c2937d34f5f247a21dc07a1c6e40611e1c695501",
          "md5": "b7110ec9c262c8a1fbb7687b9a704015"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1.0-sources.jar",
          "url": "webview_flutter_android_release-1.0-sources.jar",
          "size": 61506,
          "sha512": "e6568ae0bc08aa93f82969eb5163670b978aa0ce9d7afad819121949388a63e6250769aff10c8aa49cb75695eb40e109a95339bf591b3c1670de27e43728cd63",
          "sha256": "89a1b253e75696a2014ff86d66e8be4957a953a2dffdc90208065efbfe52ab76",
          "sha1": "d84f5919cb52a89638e6a5bf8e86171f7b40c9e4",
          "md5": "1afcd4ba8b50bfed2f5ca86d4a89f702"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1.0-javadoc.jar",
          "url": "webview_flutter_android_release-1.0-javadoc.jar",
          "size": 752120,
          "sha512": "9e7216436745e707b59bd6fc1bdcb334ed587b093311eb557933a01b22f31205c9531e837f856d12559b02c91f3ca658666b11030bfb5c2aea13d2b2747d7f88",
          "sha256": "bdb09aab88725f3d3a1bcce2507699b4fd13d9255ea007d68deb61cec8af9f5c",
          "sha1": "37274507a39af2bbc9d6bf99a23349dea26f7475",
          "md5": "ca4bff9aa149a0654046c0caf3282721"
        }
      ]
    }
  ]
}
